public class homePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
        dir= new Directory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ins_key_inp = new javax.swing.JTextField();
        insert_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        op_box = new javax.swing.JTextArea();
        search_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("insert key : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 30, 127, 38);

        ins_key_inp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_key_inpActionPerformed(evt);
            }
        });
        jPanel1.add(ins_key_inp);
        ins_key_inp.setBounds(280, 30, 114, 38);

        insert_button.setBackground(new java.awt.Color(0, 0, 0));
        insert_button.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        insert_button.setForeground(new java.awt.Color(255, 255, 255));
        insert_button.setText("insert");
        insert_button.setBorderPainted(false);
        insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(insert_button);
        insert_button.setBounds(440, 30, 110, 40);

        op_box.setEditable(false);
        op_box.setBackground(new java.awt.Color(51, 51, 51));
        op_box.setColumns(20);
        op_box.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        op_box.setForeground(new java.awt.Color(255, 255, 255));
        op_box.setRows(5);
        jScrollPane1.setViewportView(op_box);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 80, 650, 350);

        search_button.setBackground(new java.awt.Color(0, 0, 0));
        search_button.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        search_button.setForeground(new java.awt.Color(255, 255, 255));
        search_button.setText("search");
        search_button.setBorderPainted(false);
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(search_button);
        search_button.setBounds(590, 30, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("IMAGE LOCATION")); // NOI18N
        jLabel2.setText("jlabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 840, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        int key =Integer.parseInt(ins_key_inp.getText());
        int hash_val=key%16;
        int ret =  dir.insert_dir(hash_val,key,dir);
        if(ret==1){
        print_gui(dir);
        }
        else
        {
            op_box.setText("this element cant be inserted");
        }
    }                                             

    public void print_gui(Directory dir)
    {
        int current_size=1;
        for(int i=0;i<dir.gd;i++)
        {
            current_size*=2;
        }
        op_box.setText("global depth : "+dir.gd+"\nDirectory\tBucket\t\tlocal depth\n");
        for(int i=0;i<current_size;i++)
        {
            //System.out.print("Directory "+i+" : ");
            int temp=i;
            int[] k=new int[4];
            //int val=0;
            for(int j=0;j<4;j++)
            {
                k[j]=temp%2;
                temp=temp/2;
                //int l;
                //for(l=0;l<j;l++)
                //{
                //    k=k*10;
                //}
                //val=(10*val)+k;
            }
            for(int j=3;j>=0;j--)
            {
                op_box.append(String.valueOf(k[j]));
            }
            op_box.append("\t");
//            for(int j=0;j<;j++)
//            {
//                op_box.append(" ");
//            }
            if(dir.directory[i].a_full==true)
            {
                //System.out.print(dir.directory[i].a);
                //System.out.print(" ");
                op_box.append(String.valueOf(dir.directory[i].a));
                if(dir.directory[i].b_full==true)
                {
                    //System.out.print(dir.directory[i].b);
                    //System.out.print(" ");
                    op_box.append(String.valueOf(","+dir.directory[i].b));
                    if(dir.directory[i].c_full==true)
                    {
                        //System.out.print(dir.directory[i].c);
                        op_box.append(String.valueOf(","+dir.directory[i].c));
                    }
                }
            }
            //System.out.print("\n");
            op_box.append("\t\t"+dir.directory[i].ld+"\n");
        }
    }
    private void ins_key_inpActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        int key = Integer.parseInt(ins_key_inp.getText());
        int val;
        val = dir.search(dir,key);
        if(val==-1)
        {
            op_box.setText("element not found");
        }
        else
        {
            op_box.setText("element found at bucket from pointer at ");
            int temp=val;
            int[] k=new int[4];
            //int val=0;
            for(int j=0;j<4;j++)
            {
                k[j]=temp%2;
                temp=temp/2;
                //int l;
                //for(l=0;l<j;l++)
                //{
                //    k=k*10;
                //}
                //val=(10*val)+k;
            }
            for(int j=3;j>=0;j--)
            {
                op_box.append(String.valueOf(k[j]));
            }
           // op_box.append("\t");
        }
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //initialisation of the directory
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify                     
    private javax.swing.JTextField ins_key_inp;
    private javax.swing.JButton insert_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea op_box;
    private javax.swing.JButton search_button;
    // End of variables declaration                   
    Directory dir;
}
